/**
 * Re-downloads the self-hosted webfonts and regenerates src/styles/fonts.css.
 *
 * The handoff loads Archivo and JetBrains Mono from Google Fonts via @import. We serve them
 * from our own origin instead: one less third-party connection on the critical path, a
 * self-contained build, and no visitor IPs sent to a third party.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises'

const SPEC =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap'
// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
// English-language site: the Cyrillic, Greek and Vietnamese subsets would triple the payload.
const SUBSETS = new Set(['latin', 'latin-ext'])

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text()
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]

await mkdir('public/fonts', { recursive: true })

const faces = []
for (const [, subset, block] of blocks) {
  if (!SUBSETS.has(subset)) continue
  const family = /font-family:\s*'([^']+)'/.exec(block)[1]
  const weight = /font-weight:\s*(\d+)/.exec(block)[1]
  const range = /unicode-range:\s*([^;]+);/.exec(block)[1].trim()
  const url = /url\((\S+?)\)/.exec(block)[1]

  const file = `${family.toLowerCase().replace(/ /g, '-')}-${weight}-${subset}.woff2`
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer())
  await writeFile(`public/fonts/${file}`, bytes)

  faces.push(`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${range};
}`)
  console.log('wrote public/fonts/' + file)
}

await writeFile(
  'src/styles/fonts.css',
  `/* Self-hosted webfonts — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n${faces.join('\n\n')}\n`,
)
console.log(`wrote src/styles/fonts.css (${faces.length} faces)`)
